# Generated by Django 4.1.5 on 2023-01-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_qty',
        ),
    ]
